import React from 'react';
import { Button } from '@mui/material';
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';

const ExportPDFButton = ({ results, inputs, isSimpleAnalysis }) => {
    const generatePDF = () => {
        // For now, we'll create a simple HTML-based solution
        // In a real implementation, you'd use libraries like jsPDF or Puppeteer
        
        const formatCurrency = (value) => {
            return new Intl.NumberFormat('en-GB', {
                style: 'currency',
                currency: 'GBP',
                minimumFractionDigits: 0,
                maximumFractionDigits: 0,
            }).format(value);
        };

        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>Quantify Lite - Savings Optimization Report</title>
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        margin: 40px;
                        color: #333;
                    }
                    .header {
                        text-align: center;
                        border-bottom: 2px solid #8a4d80;
                        padding-bottom: 20px;
                        margin-bottom: 30px;
                    }
                    .section {
                        margin-bottom: 30px;
                    }
                    .investment-item {
                        border: 1px solid #ddd;
                        border-radius: 8px;
                        padding: 15px;
                        margin-bottom: 10px;
                        background-color: #f9f9f9;
                    }
                    .summary-box {
                        background-color: #e8f5e8;
                        border: 1px solid #4caf50;
                        border-radius: 8px;
                        padding: 20px;
                        margin-bottom: 20px;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-bottom: 20px;
                    }
                    th, td {
                        border: 1px solid #ddd;
                        padding: 8px;
                        text-align: left;
                    }
                    th {
                        background-color: #f2f2f2;
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Quantify Lite</h1>
                    <h2>Savings Optimization Report</h2>
                    <p>Generated on ${new Date().toLocaleDateString('en-GB')}</p>
                </div>

                <div class="section">
                    <h3>Your Inputs</h3>
                    <table>
                        <tr>
                            <th>Annual Earnings</th>
                            <td>${formatCurrency(inputs.earnings)}</td>
                        </tr>
                        <tr>
                            <th>ISA Allowance Used</th>
                            <td>${formatCurrency(inputs.isa_allowance_used)}</td>
                        </tr>
                        <tr>
                            <th>Analysis Type</th>
                            <td>${isSimpleAnalysis ? 'Simple Analysis' : 'Detailed Breakdown'}</td>
                        </tr>
                    </table>
                </div>

                ${results.summary ? `
                <div class="section">
                    <h3>Summary Results</h3>
                    <div class="summary-box">
                        <h4>Total Annual Return: ${formatCurrency(results.summary.net_annual_interest)}</h4>
                        <p><strong>Total Investment:</strong> ${formatCurrency(results.summary.total_investment)}</p>
                        <p><strong>Effective Rate:</strong> ${results.summary.effective_rate?.toFixed(2)}%</p>
                        <p><strong>Tax Saved:</strong> ${formatCurrency(results.summary.tax_saved)}</p>
                    </div>
                </div>
                ` : ''}

                <div class="section">
                    <h3>Recommended Investments</h3>
                    ${results.investments.map(investment => `
                        <div class="investment-item">
                            <h4>${investment.account_name}</h4>
                            <p><strong>Amount to Invest:</strong> ${formatCurrency(investment.amount)}</p>
                            <p><strong>Annual Equivalent Rate:</strong> ${investment.aer}%</p>
                            <p><strong>Term:</strong> ${investment.term}</p>
                            <p><strong>ISA:</strong> ${investment.is_isa ? 'Yes' : 'No'}</p>
                        </div>
                    `).join('')}
                </div>

                <div class="section">
                    <p><em>This report was generated by Quantify Lite. Please verify all information before making investment decisions.</em></p>
                </div>
            </body>
            </html>
        `;

        // Open in new window for printing/saving as PDF
        const newWindow = window.open('', '_blank');
        newWindow.document.write(htmlContent);
        newWindow.document.close();
        
        // Trigger print dialog
        setTimeout(() => {
            newWindow.print();
        }, 500);
    };

    return (
        <Button
            variant="outlined"
            startIcon={<PictureAsPdfIcon />}
            onClick={generatePDF}
            sx={{ mt: 2 }}
        >
            Export PDF Report
        </Button>
    );
};

export default ExportPDFButton;